### ISSUE TITLE
Installation error with fairseq

### ISSUE THREAD

**Issue by matsui528** [naist-nlp/knn-seq#104]
I have the following error when installing knn-seq.

```console
$ pip install ./

Processing /workspaces/knn-seq
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fairseq==0.12.1 (from knn-seq==0.1.0)
  Downloading fairseq-0.12.1.tar.gz (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 13.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/local/python/3.10.8/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/python/3.10.8/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/python/3.10.8/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-rq2r0mqs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-rq2r0mqs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-rq2r0mqs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "<string>", line 18, in write_version_py
      FileNotFoundError: [Errno 2] No such file or directory: 'fairseq/version.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

This error is reported [here](https://github.com/facebookresearch/fairseq/issues/4501). This problem is solved by updating the version of `fairseq` from 0.12.1 to 0.12.2 (I confirmed)
https://github.com/naist-nlp/knn-seq/blob/396529f06908ef893a4120c258019f208cfe05d0/pyproject.toml#L13

I will make a PR if you like.

<details><summary>Tested environment</summary><div>

- Create a fresh codespace (Ubuntu 20.04)
- Run `pip install ./`

Version of python and pip:
```console
@matsui528 ➜ /workspaces/knn-seq (main) $ which python
/home/codespace/.python/current/bin/python
@matsui528 ➜ /workspaces/knn-seq (main) $ python --version
Python 3.10.8

@matsui528 ➜ /workspaces/knn-seq (main) $ which pip
/home/codespace/.python/current/bin/pip
@matsui528 ➜ /workspaces/knn-seq (main) $ pip --version
pip 23.2.1 from /usr/local/python/3.10.8/lib/python3.10/site-packages/pip (python 3.10)
```
</div></details>

**Comment by de9uch1** [comment]
Thank you for your report.
It is caused by a fairseq-specific problem.

There are 3 versions in fairseq v0.12.*, but each has a different problem.
- v0.12.1: We can install it with python 3.8 but not with >= 3.9.
- v0.12.2: There is a critical bug in the upstream codes and our unit tests cannot pass.
- v0.12.3: No problem, but we need to install from only the source via git because the wheel package is not created.

Thus, we'll update the requirements to depend on v0.12.3 (git).

**Comment by matsui528** [comment]
Thank you!
